---
- name: Create monitoring directory
  ansible.builtin.file:
    path: /srv/monitoring
    state: directory
    mode: '0700'

- name: Template wordpress-db check config
  ansible.builtin.template:
    src: wordpress-db.j2
    dest: /srv/monitoring/wordpress-db.cnf
    mode: '0700'

- name: Template acs-db check config
  ansible.builtin.template:
    src: acs-db.j2
    dest: /srv/monitoring/acs-db.cnf
    mode: '0700'

- name: slagios
  community.general.docker_container:
    name: slagios
    image: jbros/slagios
    networks:
      - name: wp_db_net
      - name: nginx_net
      - name: acs_db_net
    restart_policy: always
    volumes:
      - "/srv/monitoring:/config"
    expose: 80
    env:
      VIRTUAL_HOST: "slagios.hal9k.dk"
      LETSENCRYPT_HOST: "slagios.hal9k.dk"
      SLAGIOS_interval: 30s
      SLAGIOS_rinterval: 30s
      SLAGIOS_check_wp: /usr/lib/nagios/plugins/check_http -H www.hal9k.dk -f follow -t 10
      SLAGIOS_check_wp_ssl: /usr/lib/nagios/plugins/check_ssl_cert -H drillpress.hal9k.dk --sni www.hal9k.dk --cn www.hal9k.dk -t 10
      SLAGIOS_interval_wp_ssl: 1h
      SLAGIOS_check_wp2: /usr/lib/nagios/plugins/check_http -H xn--befridinelmler-vib.dk -f follow -t 10
      SLAGIOS_check_wp2_ssl: /usr/lib/nagios/plugins/check_ssl_cert -H drillpress.hal9k.dk --sni xn--befridinelmler-vib.dk --cn xn--befridinelmler-vib.dk -t 10
      SLAGIOS_interval_wp2_ssl: 1h
      SLAGIOS_check_wp_mysql: /usr/lib/nagios/plugins/check_mysql -d {{ wordpress.db.name }} -H wordpress-db -P 3306 -f /config/wordpress-db.cnf
      SLAGIOS_check_wiki: /usr/lib/nagios/plugins/check_http -H wiki.hal9k.dk -f follow -t 10
      SLAGIOS_check_wiki_ssl: /usr/lib/nagios/plugins/check_ssl_cert -H drillpress.hal9k.dk --sni wiki.hal9k.dk --cn wiki.hal9k.dk -t 10
      SLAGIOS_interval_wiki_ssl: 1h
      SLAGIOS_check_acs_mysql: /usr/lib/nagios/plugins/check_mysql -d {{ acs.dbname }} -H acs-db -P 3306 -f /config/acs-db.cnf
      SLAGIOS_check_acs: /usr/lib/nagios/plugins/check_http -H {{ acs.hostname }} -f follow -t 10
      SLAGIOS_check_acs_ssl: /usr/lib/nagios/plugins/check_ssl_cert -H drillpress.hal9k.dk --sni {{ acs.hostname }} --cn {{ acs.hostname }} -t 10
      SLAGIOS_interval_acs_ssl: 1h
      SLAGIOS_check_acs_sync: /usr/lib/nagios/plugins/check_file_age -w 600 -c 900 -f /config/acsv2/acs-sync-status
      SLAGIOS_interval_acs_sync: 5m
      SLAGIOS_check_emojiconsan: /usr/lib/nagios/plugins/check_file_age -w 300 -c 400 -f /config/emojiconsan/emojiconsan.stamp
      SLAGIOS_interval_emojiconsan: 5m
      SLAGIOS_check_cams_heartbeat: /usr/lib/nagios/plugins/check_file_age -w 43200 -c 86400 /config/acsgw/cam-heartbeat
      SLAGIOS_interval_cams_heartbeat: 5m
      SLAGIOS_check_acs_heartbeat: /usr/lib/nagios/plugins/check_file_age -w 120 -c 300 /config/acsgw/acs-heartbeat
      SLAGIOS_interval_acs_heartbeat: 5m
      SLAGIOS_check_woodshop_heartbeat: /usr/lib/nagios/plugins/check_file_age -w 360 -c 600 /config/acsgw/bacs-heartbeat
      SLAGIOS_interval_woodshop_heartbeat: 5m
      SLAGIOS_check_barndoor_heartbeat: /usr/lib/nagios/plugins/check_file_age -w 360 -c 600 /config/acsgw/barndoor-heartbeat
      SLAGIOS_interval_barndoor_heartbeat: 5m
      SLAGIOS_check_camctl_heartbeat: /usr/lib/nagios/plugins/check_file_age -w 300 -c 600 /config/acsgw/camctl-heartbeat
      SLAGIOS_interval_camctl_heartbeat: 5m
      SLAGIOS_check_disk_root: /usr/lib/nagios/plugins/check_disk -w 75 -c 85 -p /
      SLAGIOS_interval_disk_root: 15m
      SLAGIOS_rinterval_disk_root: 15m
      SLAGIOS_webhook: "{{ slagios.webhook }}"
      SLAGIOS_signingkey: "{{ slagios.signing_key }}"
      SLAGIOS_slashcmd: "/slagios"
