---
- name:
  community.general.docker_container:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    volumes:
      - "/srv/nginx/certs:/etc/nginx/certs"
      - "/srv/nginx/vhost.d:/etc/nginx/vhost.d"
      - "/srv/nginx/html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
      - "443:443"
    restart_policy: always

- name:
  community.general.docker_container:
    name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from: nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      DEFAULT_EMAIL: "{{ acme.email }}"

