---
wordpress:
  db:
    name: wordpress
    user: wordpress
    pass: "{{ vault.wordpress.dbpass }}"
  hostname: "www.hal9k.dk,hal9k.dk"
mysql:
  rootpass: "{{ vault.mysql.rootpass }}"
acs:
  rootpass: "{{ vault.acs.rootpass }}"
  pass: "{{ vault.acs.dbpass }}"
  hostname: "acs.hal9k.dk"
acme:
  email: "{{ vault.acme.email }}"
dokuwiki:
  hostname: wiki.hal9k.dk
qrredirect:
  hostname: qr.hal9k.dk
ssh:
  users:
    - bullestock
    - fasmide
    - jbro
watchtower:
  slack_hook_url: "{{ vault.watchtower.slack_hook_url }}"
backblaze:
  keyID: "{{ vault.backblaze.keyID }}"
  keyName: drillpress
  applicationKey: "{{ vault.backblaze.applicationKey }}"
restic:
  repopass: "{{ vault.restic.repopass }}"
slagios:
  webhook: "{{ vault.slagios.webhook }}"
  signing_key: "{{ vault.slagios.signing_key }}"
