---
wordpress:
  db:
    name: wordpress
    user: wordpress
    pass: "{{ vault.wordpress.dbpass }}"
  hostname: www2.hal9k.dk
mysql:
  rootpass: "{{ vault.mysql.rootpass }}"
acme:
  email: "{{ vault.acme.email }}"
dokuwiki:
  hostname: wiki2.hal9k.dk
ssh:
  users:
    - bullestock
    - fasmide
    - jbro
watchtower:
  slack_hook_url: "{{ vault.watchtower.slack_hook_url }}"
backblaze:
  keyID: "{{ vault.backblaze.keyID }}"
  keyName: drillpress
  applicationKey: "{{ vault.backblaze.applicationKey }}"
restic:
  repopass: "{{ vault.restic.repopass }}"
