---
wordpress:
  db:
    name: wordpress
    user: wordpress
    pass: "{{ vault.wordpress.dbpass }}"
  hostname: "www.hal9k.dk,hal9k.dk"
mysql:
  rootpass: "{{ vault.mysql.rootpass }}"
acs:
  rootpass: "{{ vault.acs.rootpass }}"
  dbname: acs
  dbuser: acs
  dbpass: "{{ vault.acs.dbpass }}"
  hostname: "panopticon.hal9k.dk"
  fluser: "{{ vault.acs.fluser }}"
  flpass: "{{ vault.acs.flpass }}"
acsgw:
  hostname: "acsgateway.hal9k.dk"
  slacktoken: "{{ vault.acsgw.slacktoken }}"
  slackteam: "T04LP1S7R"
  acstoken: "{{ vault.acsgw.acstoken }}"
  webhook: "{{ vault.acsgw.webhook }}"
  actionusers: "{{ vault.acsgw.actionusers }}"
  camera:
    token: "{{ vault.acsgw.camera.token }}"
    defaults:
      keepalive: 600
      pixel_threshold: 10
      percent_threshold: 2
acme:
  email: "{{ vault.acme.email }}"
dokuwiki:
  hostname: wiki.hal9k.dk
qrredirect:
  hostname: qr.hal9k.dk
ssh:
  users:
    - bullestock
    - fasmide
    - jbro
watchtower:
  slack_hook_url: "{{ vault.watchtower.slack_hook_url }}"
backblaze:
  keyID: "{{ vault.backblaze.keyID }}"
  keyName: drillpress
  applicationKey: "{{ vault.backblaze.applicationKey }}"
restic:
  repopass: "{{ vault.restic.repopass }}"
slagios:
  webhook: "{{ vault.slagios.webhook }}"
  signing_key: "{{ vault.slagios.signing_key }}"
minio:
  username: hal9k
  password: "{{ vault.minio.password }}"
  hostname: minio.hal9k.dk
