---
- name: MySQL server
  community.general.docker_container:
    name: db
    image: "mysql:8"
    volumes:
      - "/srv/mysql:/var/lib/mysql"
    restart_policy: always
    env:
       MYSQL_ROOT_PASSWORD: "{{ mysql.rootpass }}"
       MYSQL_DATABASE: "{{ wordpress.db.name }}"
       MYSQL_USER: "{{ wordpress.db.user }}"
       MYSQL_PASSWORD: "{{ wordpress.db.pass }}"

- name: Wordpress
  community.general.docker_container:
    name: wordpress
    image: "wordpress:latest"
    ports:
      - "8000:80"
    restart_policy: always
    links:
      - db
    env:
      WORDPRESS_DB_HOST: "db:{{ mysql.port }}"
      WORDPRESS_DB_USER: "{{ wordpress.db.user }}"
      WORDPRESS_DB_PASSWORD: "{{ wordpress.db.pass }}"
      WORDPRESS_DB_NAME: "{{ wordpress.db.name }}"
