---
- name: Wordpress MySQL server
  community.general.docker_container:
    name: wordpress-db
    image: "mysql:8"
    volumes:
      - "/srv/mysql:/var/lib/mysql"
    restart_policy: always
    env:
       MYSQL_ROOT_PASSWORD: "{{ mysql.rootpass }}"
       MYSQL_DATABASE: "{{ wordpress.db.name }}"
       MYSQL_USER: "{{ wordpress.db.user }}"
       MYSQL_PASSWORD: "{{ wordpress.db.pass }}"

- name: Wordpress
  community.general.docker_container:
    name: wordpress
    image: "wordpress:latest"
    restart_policy: always
    links:
      - wordpress-db
    expose: 80
    env:
      VIRTUAL_HOST: www2.hal9k.dk
      LETSENCRYPT_HOST: www2.hal9k.dk
      WORDPRESS_DB_HOST: "wordpress-db:3306"
      WORDPRESS_DB_USER: "{{ wordpress.db.user }}"
      WORDPRESS_DB_PASSWORD: "{{ wordpress.db.pass }}"
      WORDPRESS_DB_NAME: "{{ wordpress.db.name }}"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'https://www2.hal9k.dk' );
        define( 'WP_SITEURL', 'https://www2.hal9k.dk' );
