---
- name: ACS database network
  community.docker.docker_network:
    name: acs_db_net

- name: ACS
  community.general.docker_container:
    name: acsv3
    image: bullestock/acsv3
    networks:
      - name: acs_db_net
      - name: nginx_net
    volumes:
      - "/srv/monitoring/acsv3:/opt/app/acsv3/monitoring"
    restart_policy: always
    expose: 8020
    env:
      VIRTUAL_HOST: "{{ acs.hostname }}"
      LETSENCRYPT_HOST: "{{ acs.hostname }}"
      DJANGO_SECRET_KEY: acs.django_secret_key
      DB_PASSWORD: "{{ acs.dbpass }}"
      FL_USER: "{{ acs.fluser }}"
      FL_PASS: "{{ acs.flpass }}"

- name: ACS MySQL server
  community.general.docker_container:
    name: acs-db-8
    image: "mysql:8"
    volumes:
      - "/srv/acs/mysql8:/var/lib/mysql"
    networks:
      - name: acs_db_net
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ acs.rootpass }}"
      MYSQL_DATABASE: acs
      MYSQL_USER: acs
      MYSQL_PASSWORD: "{{ acs.dbpass }}"

