---
- name: ACS database network
  community.docker.docker_network:
    name: acs_db_net

- name: ACS
  community.general.docker_container:
    name: acsv2
    image: bullestock/acsv2
    networks:
      - name: acs_db_net
      - name: nginx_net
    restart_policy: always
    expose: 80
    env:
      DJANGO_SECRET_KEY: acs.django_secret_key
      DB_PASSWORD: acs.db.pass

- name: ACS MySQL server
  community.general.docker_container:
    name: acs-db
    image: "mysql:5"
    volumes:
      - "/srv/acs/mysql:/var/lib/mysql"
    networks:
      - name: acs_db_net
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ acs.db.rootpass }}"
      MYSQL_DATABASE: acs
      MYSQL_USER: acs
      MYSQL_PASSWORD: "{{ acs.db.pass }}"

