---
- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    update_cache: "yes"

- name: Template /etc/iptables/rules.v4
  ansible.builtin.template:
    src: rules_v4.j2
    dest: /etc/iptables/rules.v4
  notify: restart iptables

- name: Template /etc/iptables/rules.v6
  ansible.builtin.template:
    src: rules_v6.j2
    dest: /etc/iptables/rules.v6
  notify: restart iptables
