---
- name: Create camera user
  ansible.builtin.user:
    name: camera

- name: create camera archives
  ansible.builtin.file:
    path: "{{ item }}"
    owner: camera
    group: camera
    state: directory
    mode: "700"
  loop:
    - /home/camera/cam1
    - /home/camera/cam2
    - /home/camera/cam3
    - /home/camera/cam4
    - /home/camera/cam5

- name: Upload public key
  ansible.posix.authorized_key:
    user: camera
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"

- name: Upload prune cam archive script to /usr/local/lib
  ansible.builtin.copy:
    src: prune_cam_archive.sh
    dest: /usr/local/lib/prune_cam_archive.sh
    mode: '0700'

- name: Install prune cam archive service
  ansible.builtin.copy:
    src: prune_cam_archive.service
    dest: /etc/systemd/system/

- name: Install prune cam archive timer
  ansible.builtin.copy:
    src: prune_cam_archive.timer
    dest: /etc/systemd/system/

- name: Enable prune cam archive schedule
  ansible.builtin.systemd:
    daemon_reload: yes
    name: prune_cam_archive.timer
    enabled: "yes"
    state: started
