---
- name: ACS Gateway
  community.general.docker_container:
    name: acsgw
    image: bullestock/acs-gateway
    networks:
      - name: nginx_net
    expose: 5000
    env:
      VIRTUAL_HOST: "{{ acsgw.hostname }}"
      LETSENCRYPT_HOST: "{{ acsgw.hostname }}"
      VALIDATION_TOKEN: "{{ acsgw.apitoken }}"
