---
- name: ACS Gateway
  community.general.docker_container:
    name: acsgw
    image: bullestock/acs-gateway
    networks:
      - name: nginx_net
    volumes:
      - "/srv/monitoring/acsgw:/opt/service/monitoring"
      - "/srv/acsgw:/opt/service/persistent"
    expose: 5000
    env:
      VIRTUAL_HOST: "{{ acsgw.hostname }}"
      LETSENCRYPT_HOST: "{{ acsgw.hostname }}"
      SLACK_VERIFICATION_TOKEN: "{{ acsgw.slacktoken }}"
      SLACK_WRITE_TOKEN: "{{ acsgw.slackwritetoken }}"
      SLACK_TEAM_ID: "{{ acsgw.slackteam }}"
      ACS_VERIFICATION_TOKEN: "{{ acsgw.acstoken }}"
      ACS_ACTION_USERS: "{{ acsgw.acsactionusers }}"
      CAM_ACTION_USERS: "{{ acsgw.camactionusers }}"
      CAMERA_VERIFICATION_TOKEN: "{{ acsgw.camera.token }}"
      CAMERA_DEFAULT_KEEPALIVE: "{{ acsgw.camera.defaults.keepalive }}"
      CAMERA_DEFAULT_PIXEL_THRESHOLD: "{{ acsgw.camera.defaults.pixel_threshold }}"
      CAMERA_DEFAULT_PERCENT_THRESHOLD: "{{ acsgw.camera.defaults.percent_threshold }}"
      CAMCTL_VERIFICATION_TOKEN: "{{ acsgw.camctl.token }}"

- name: Upload prune logs script to /usr/local/lib
  ansible.builtin.copy:
    src: acs_prune_logs.sh
    dest: /usr/local/lib/acs_prune_logs.sh
    mode: '0700'

- name: Install prune logs service
  ansible.builtin.copy:
    src: acs_prune_logs.service
    dest: /etc/systemd/system/

- name: Install prune logs timer
  ansible.builtin.copy:
    src: acs_prune_logs.timer
    dest: /etc/systemd/system/

- name: Enable prune logs schedule
  ansible.builtin.systemd:
    daemon_reload: yes
    name: acs_prune_logs.timer
    enabled: "yes"
    state: started
