---
- name: ACS Gateway
  community.general.docker_container:
    name: acsgw
    image: bullestock/acs-gateway
    networks:
      - name: nginx_net
    volumes:
      - "/srv/monitoring/acsgw:/opt/service/monitoring"
      - "/srv/acsgw:/opt/service/persistent"
    expose: 5000
    env:
      VIRTUAL_HOST: "{{ acsgw.hostname }}"
      LETSENCRYPT_HOST: "{{ acsgw.hostname }}"
      SLACK_VERIFICATION_TOKEN: "{{ acsgw.slacktoken }}"
      SLACK_TEAM_ID: "{{ acsgw.slackteam }}"
      ACS_VERIFICATION_TOKEN: "{{ acsgw.acstoken }}"
      ACS_ACTION_USERS: "{{ acsgw.acsactionusers }}"
      CAM_ACTION_USERS: "{{ acsgw.camactionusers }}"
      CAMERA_VERIFICATION_TOKEN: "{{ acsgw.camera.token }}"
      CAMERA_DEFAULT_KEEPALIVE: "{{ acsgw.camera.defaults.keepalive }}"
      CAMERA_DEFAULT_PIXEL_THRESHOLD: "{{ acsgw.camera.defaults.pixel_threshold }}"
      CAMERA_DEFAULT_PERCENT_THRESHOLD: "{{ acsgw.camera.defaults.percent_threshold }}"

