---
- name: ACS Gateway
  community.general.docker_container:
    name: acsgw
    image: bullestock/acs-gateway
    networks:
      - name: nginx_net
    expose: 5000
    env:
      VIRTUAL_HOST: "{{ acsgw.hostname }}"
      LETSENCRYPT_HOST: "{{ acsgw.hostname }}"
      SLACK_VERIFICATION_TOKEN: "{{ acsgw.slacktoken }}"
      SLACK_TEAM_ID: "{{ acsgw.slackteam }}"
      ACS_VERIFICATION_TOKEN: "{{ acsgw.acstoken }}"
      ACTION_USERS: "{{ acsgw.actionusers }}"
      CAMERA_VERIFICATION_TOKEN: "{{ acsgw.camera.token }}"
      CAMERA_DEFAULTS: "{{ acsgw.camera.defaults }}"
      CAMERA_OVERRIDES: "{{ acsgw.camera.overrides }}"
