---
- name: Set hostname
  hosts: drillpress.hal9k.dk
  tasks:
    - name: drillpress.hal9k.dk
      ansible.builtin.hostname:
        name: drillpress.hal9k.dk

- name: Install docker
  hosts: drillpress.hal9k.dk
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.docker
    - geerlingguy.pip

- name: Setup Watchtower
  hosts: drillpress.hal9k.dk
  tags: watchtower
  roles:
    - watchtower

- name: Setup v6 NAT for docker
  hosts: drillpress.hal9k.dk
  tags: docker_ipv6
  roles:
    - docker_ipv6

- name: Setup firewall
  hosts: drillpress.hal9k.dk
  tags: iptables
  roles:
    - iptables

- name: Setup nginx docker proxy with SSL
  hosts: drillpress.hal9k.dk
  tags: nginx_proxy
  roles:
    - nginx_proxy

- name: Setup WordPress
  hosts: drillpress.hal9k.dk
  tags: wordpress
  roles:
    - wordpress

- name: Setup Dokuwiki
  hosts: drillpress.hal9k.dk
  tags: dokuwiki
  roles:
    - dokuwiki

- name: Setup monitoring
  hosts: drillpress.hal9k.dk
  tags: monitoring
  roles:
    - monitoring

- name: Backup
  hosts: drillpress.hal9k.dk
  tags: backup
  roles:
    - backup

- name: Setup ACS
  hosts: drillpress.hal9k.dk
  tags: acs
  roles:
    - acs

- name: Setup ACS Gateway
  hosts: drillpress.hal9k.dk
  tags: acsgw
  roles:
    - acsgw

- name: Setup MinIO
  hosts: drillpress.hal9k.dk
  tags: minio
  roles:
    - minio
