---
- name: Install docker
  hosts: drillpress.hal9k.dk
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.docker
    - geerlingguy.pip

- name: Setup nginx docker proxy with SSL
  hosts: drillpress.hal9k.dk
  tags: nginx_proxy
  roles:
    - nginx_proxy

- name: Setup WordPress
  hosts: drillpress.hal9k.dk
  tags: wordpress
  roles:
    - wordpress

- name: Seup Dokuwiki
  hosts: drillpress.hal9k.dk
  tags: dokuwiki
  roles:
    - dokuwiki

- name: Setup Watchtower
  hosts: drillpress.hal9k.dk
  tags: watchtower
  roles:
    - watchtower

- name: Setup firewall
  hosts: drillpress.hal9k.dk
  tags: iptables
  roles:
    - iptables
