---
- name: Common tasks for all nodes
  hosts: all
  roles:
    - common

- name: Setup sshd
  hosts: all
  roles:
    - sshd

- name: Install docker
  hosts: servers
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.docker
    - geerlingguy.pip

- name: Setup WordPress
  hosts: servers
  tags: cur
  roles:
    - wordpress

