---
- name: Common tasks for all nodes
  hosts: all
  tags: common
  roles:
    - common

- name: Setup sshd
  hosts: all
  tags: sshd
  roles:
    - sshd

- name: Update ssh access from github
  hosts: all
  vars:
    users:
      - fasmide
      - jbro
  tags: update_ssh_keys
  roles:
    - update_ssh_keys

- import_playbook: drillpress.yml
