---
- name: Common tasks for all nodes
  hosts: all
  roles:
    - common

- name: Setup sshd
  hosts: all
  roles:
    - sshd

#- name: Install docker
#  hosts: servers
#  roles:
#    - geerlingguy.docker
