---
- name: Create backup directory
  ansible.builtin.file:
    path: /srv/emojis
    state: directory
    mode: '0700'

- name: emojiconsan
  community.general.docker_container:
    name: emojiconsan
    image: bullestock/emojiconsan
    restart_policy: always
    volumes:
      - "/srv/emojis:/emojis"
      - "/srv/monitoring/emojiconsan:/monitoring"
    env:
      TOKEN: "{{ emojiconsan.token }}"
      HOOK: "{{ emojiconsan.hook }}"
