- name: MinIO
  community.general.docker_container:
    name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    restart_policy: always
    volumes:
    - "/srv/minio:/data"
    expose:
    - 9000
    - 9001
    env:
      MINIO_ROOT_USER: "{{ minio.username }}"
      MINIO_ROOT_PASSWORD: "{{ minio.password }}"
      MINIO_ACCESS_KEY: "{{ minio.accesskey }}"
      MINIO_SECRET_KEY: "{{ minio.secretkey }}"
