- name: Copy nginx per-host config
  ansible.builtin.copy:
    src: minio
    dest: /srv/nginx-proxy/vhost.d/minio.hal9k.dk

- name: MinIO
  community.general.docker_container:
    name: minio
    image: minio/minio:RELEASE.2022-01-08T03-11-54Z.hotfix.631cdd868
    command: server /data --console-address ":9001"
    restart_policy: always
    volumes:
      - "/srv/minio:/data"
    expose:
      - 9000
    networks:
      - name: nginx_net
    env:
      MINIO_ROOT_USER: "{{ minio.username }}"
      MINIO_ROOT_PASSWORD: "{{ minio.password }}"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
      VIRTUAL_HOST: "{{ minio.hostname }}"
      LETSENCRYPT_HOST: "{{ minio.hostname }}"

- name: Upload prune cam archive script to /usr/local/lib
  ansible.builtin.copy:
    src: minio_prune_cam_archive.sh
    dest: /usr/local/lib/minio_prune_cam_archive.sh
    mode: '0700'

- name: Install prune cam archive service
  ansible.builtin.copy:
    src: minio_prune_cam_archive.service
    dest: /etc/systemd/system/

- name: Install prune cam archive timer
  ansible.builtin.copy:
    src: minio_prune_cam_archive.timer
    dest: /etc/systemd/system/

- name: Enable prune cam archive schedule
  ansible.builtin.systemd:
    daemon_reload: yes
    name: minio_prune_cam_archive.timer
    enabled: "yes"
    state: started
