- name: Copy nginx per-host config
  ansible.builtin.copy:
    src: minio
    dest: /srv/nginx-proxy/vhost.d/minio.hal9k.dk

- name: MinIO
  community.general.docker_container:
    name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    restart_policy: always
    volumes:
      - "/srv/minio:/data"
    expose:
      - 9000
    networks:
      - name: nginx_net
    env:
      MINIO_ROOT_USER: "{{ minio.username }}"
      MINIO_ROOT_PASSWORD: "{{ minio.password }}"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
      VIRTUAL_HOST: "{{ minio.hostname }}"
      LETSENCRYPT_HOST: "{{ minio.hostname }}"
