---
- name: Watchtower
  community.general.docker_container:
    name: watchtower
    image: nickfedor/watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    comparisons:
      volumes: strict
    restart_policy: always
    env:
      WATCHTOWER_LIFECYCLE_HOOKS: 'true'
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_NOTIFICATION_URL: "slack://hook:{{ watchtower.slack_hook_url | regex_replace('^https://hooks.slack.com/services/', '') | regex_replace('/', '-') }}@webhook"
      WATCHTOWER_SCHEDULE: 0 0 */6 * * *
      WATCHTOWER_WARN_ON_HEAD_FAILURE: 'never'
