---
- name: Watchtower
  community.general.docker_container:
    name: watchtower
    image: containrrr/watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: always
    env:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ watchtower.slack_hook_url }}"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: Drillpress
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#server"
      WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":drill:"
