---

- name: Copy nginx per-host config
  ansible.builtin.copy:
    src: dokuwiki
    dest: /srv/nginx-proxy/vhost.d/wiki.hal9k.dk

- name: Dokuwiki
  community.general.docker_container:
    name: dokuwiki
    image: ghcr.io/linuxserver/dokuwiki
    volumes:
      - "/srv/dokuwiki/config:/config"
      - "/srv/dokuwiki/logs:/app/www/public/data/log"
    restart_policy: always
    expose: 80
    networks:
      - name: nginx_net
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Copenhagen
      VIRTUAL_HOST: "{{ dokuwiki.hostname }}"
      LETSENCRYPT_HOST: "{{ dokuwiki.hostname }}"

- name: QR Redirect
  community.general.docker_container:
    name: qr-redirect
    image: hal9kdk/qr-redirect:latest
    volumes_from: dokuwiki
    restart_policy: always
    expose: 80
    networks:
      - name: nginx_net
    env:
      VIRTUAL_HOST: "{{ qrredirect.hostname }}"
      LETSENCRYPT_HOST: "{{ qrredirect.hostname }}"
      NGINX_HOST: "{{ qrredirect.hostname }}"
      QRR_WATCH_FOLDER: /config/dokuwiki/data/pages
      QRR_PREFIX: "https://{{ dokuwiki.hostname }}"
      QRR_NOT_FOUND: /infrastruktur/it-services/qr/qr-kode_infoside
      QRR_REBUILD_RATE_LIMIT: "10"
      QRR_REBUILD_FREQ: "600"
      QRR_LINK_MAP: qr.txt

- name: Upload prune cam archive script to /usr/local/lib
  ansible.builtin.copy:
    src: dokuwiki_prune_logs.sh
    dest: /usr/local/lib/dokuwiki_prune_logs.sh
    mode: '0700'

- name: Install prune cam archive service
  ansible.builtin.copy:
    src: dokuwiki_prune_logs.service
    dest: /etc/systemd/system/

- name: Install prune cam archive timer
  ansible.builtin.copy:
    src: dokuwiki_prune_logs.timer
    dest: /etc/systemd/system/

- name: Enable prune cam archive schedule
  ansible.builtin.systemd:
    daemon_reload: yes
    name: dokuwiki_prune_logs.timer
    enabled: "yes"
    state: started
