name: deploy

on:
  push:
    branches: main

jobs:
  ansible:
    runs-on: ubuntu-latest
    environment:
      name: drillpress.hal9k.dk
      url: http://drillpress.hal9k.dk
    env: 
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: Fetch repository
        uses: actions/checkout@master

      - name: Play Ansible Playbook
        uses: arillso/action.playbook@0.0.4
        with:
          playbook: ansible/site.yml
          inventory: ansible/hosts
          galaxy_file: ansible/requirements.yml
          ssh_common_args: "\"-oUserKnownHostsFile=known_hosts\""
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
